version: '3.9'
services:
  estoque-facil-api-db:
    image: 'postgres:10'
    container_name: estoque-facil-api-db
    environment:
      - POSTGRES_DB=estoque_facil_api_db
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=user
    ports:
      - '15432:5432'
    volumes:
      - estoque-facil-db-volume:/var/lib/postgresql/data
networks:
  estoque-facil-api-network:
    driver: bridge
    name: estoque-facil-api-network
volumes:
  estoque-facil-db-volume:
    external: true
