server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: estoque-facil-api
  threads:
    virtual:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ESTOQUE_FACIL_DB_HOST:localhost}:${ESTOQUE_FACIL_DB_PORT:15432}/estoque_facil_api_db
    username: ${ESTOQUE_FACIL_DB_USER:user}
    password: ${ESTOQUE_FACIL_DB_PASSWORD:123456}
  flyway:
    enabled: true
    url: jdbc:postgresql://${ESTOQUE_FACIL_DB_HOST:localhost}:${ESTOQUE_FACIL_DB_PORT:15432}/estoque_facil_api_db
    user: ${ESTOQUE_FACIL_DB_USER:user}
    password: ${ESTOQUE_FACIL_DB_PASSWORD:123456}
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
      lifecycle-management: start_only
      file: compose.yaml
  data:
    web:
      pageable:
        one-indexed-parameters: true

security:
  jwt:
    # https://www.devglan.com/online-tools/hmac-sha256-online
    # https://generate-random.org/encryption-key-generator
    secret: ${JWT_SECRET:qo4MFYfQLbKWdGRLCbAHF0B/3AZttdLAc8UN/YJw5HU=}
    expiration: ${JWT_EXPIRATION:3d}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:7d}

api:
  version: @version@
